// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://sgeigsmnibaodpkgxpdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZWlnc21uaWJhb2Rwa2d4cGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTkxNTIsImV4cCI6MjA1NzczNTE1Mn0.MPw38o54DxQx5JtOv9z18sebWfB8whxAdU0ky_kgfNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);